### ISSUE TITLE
Update README examples to match npmjs.com's new interface.

### ISSUE THREAD

**Issue by stefanmaric** [eeshi/node-scrapy#10]
[npmjs.com](https://www.npmjs.com/) renewed its interface. We should update the code examples, replace the CSS selectors to match the new layout.

Completely replace examples with another good source to scrape is valid too, but examples must to be consistent.

**Comment by adrianObel** [comment]
I can take care of changing the examples and writing new ones

**Comment by stefanmaric** [comment]
Closed by #11
