### ISSUE TITLE
Unable to fetch email address

### ISSUE THREAD

**Issue by rahul-desai3** [eeshi/node-scrapy#14]
I tried running `node-scrapy` on [this sample jsFiddle](https://jsfiddle.net/b9frtkur/embedded/result/) and it couldn't get me the email address.

Here is the code that I used:

```
var scrapy = require('node-scrapy')
  , url = 'https://jsfiddle.net/b9frtkur/embedded/result/';

var model = { 
	link: { 
		selector: "a[href^='mailto']",
		get: 'href'
	}
};
 
scrapy.scrape(url, model, function(err, data) {
    if (err) return console.error(err)
    console.log(data)
});
```

The response was: `{ link: null }`

How do I get this working?

**Comment by adrianObel** [comment]
I believe this is because the content of the fiddle live inside of an iFrame @rahul-desai3

**Comment by rahul-desai3** [comment]
Gotcha.
