### ISSUE TITLE
Data model example for scraping a forum index

### ISSUE THREAD

**Issue by budda** [eeshi/node-scrapy#16]
Could you provide an example data model that shows how to scrape a forum index page listing post titles, teaser, link to full thread ?

I can't see how to return a list of data objects with the 3 items per forum post. At the moment i get a list of all forum posts, and a separate list of all urls.

**Comment by stefanmaric** [comment]
Hi @budda ,

Thanks for your question; you hit node-scrapy's greatest weakness: it cannot create collection of objects. That has been already a pain spot for us and we have made ugly workaround in our implementation; #8 is there to address that. Actually, new spec for node-scrapy is in the go.

I'm sorry we can't give you a solution, hopefully we are going to have a new (breaking API) release soon.

**Comment by budda** [comment]
At least there's hope in the near future rather than an outright "no" :)

**Comment by stefanmaric** [comment]
Possible since the v0.4.0 rewrite:

See tests number 8, 9, and 10 at: https://github.com/eeshi/node-scrapy/tree/main/test/extract
